mqtt:
  server: tcp://127.0.0.1:1883
  username: ""
  password: ""
  certification: ""
#configmap: /opt/kubeedge/deviceProfile.json
#configmap: configmap_mqtt_test.json
configmap: device-profile-config-edge120_new.json
