apiVersion: apps/v1
kind: Deployment
metadata:
  name: coap-mapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coapmapper
  template:
    metadata:
      labels:
        app: coapmapper
    spec:
      hostNetwork: true
      containers:
      - name: coap-mapper-container
        image: coapmapper:v1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kubeedge/
        - mountPath: /dev/ttyS0
          name: coap-dev0
        - mountPath: /dev/ttyS1
          name: coap-dev1
      nodeSelector:
        coap: "true"
      volumes:
      - name: config-volume
        configMap:
          name: device-profile-config-test
      - name: coap-dev0
        hostPath:
          path: /dev/ttyS0
      - name: coap-dev1
        hostPath:
          path: /dev/ttyS1
      restartPolicy: Always
